# Generated by Django 5.0.2 on 2024-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('actors', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('imageUrl', models.CharField(max_length=500)),
            ],
        ),
    ]
