# Generated by Django 5.0.2 on 2024-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxofficeapi', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='endDate',
            field=models.DateField(default='2024-04-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='startDate',
            field=models.DateField(default='2024-04-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
